---
# /roles/ssl_create/tasks/ssl_folder.yml
- name: create directories required for this role
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    recurse: no
    mode: "{{ item.mode }}"
  loop:
  - { path: "{{ private_dir }}", mode: "700" }
  - { path: "{{ cert_dir }}", mode: "710" }
